/*
 * main.c
 *
 * AUTOMATIC ENGINE LOCKING SYSTEM -- STM32 HAL implementation
 * (alcohol detection + tilt/rollover detection, either of which locks
 * the engine and triggers a GSM/GPS location alert)
 *
 * This file assumes a CubeMX-generated project where the following
 * peripherals are already initialized by MX_xxx_Init() calls (either
 * left in place if you generated this from CubeMX, or added manually
 * if hand-rolling the project):
 *
 *   ADC1   -> single channel, MQ-3 analog input
 *   TIM_x  -> one PWM channel driving the motor driver's ENABLE pin
 *   I2C1   -> LCD1602 backpack
 *   USART1 -> SIM800C GSM/GPS module
 *   GPIO   -> motor IN1/IN2, buzzer, status LED, reset button, tilt switch
 *
 * Adjust the handle names / pin macros below to match your actual
 * CubeMX pinout configuration.
 */

#include "stm32f1xx_hal.h"
#include "alcohol_sensor.h"
#include "engine_lock.h"
#include "buzzer_led.h"
#include "lcd_i2c.h"
#include "gsm_gps.h"
#include "tilt_sensor.h"
#include <stdio.h>
#include <string.h>

/* ---- Peripheral handles (normally generated by CubeMX) ---- */
ADC_HandleTypeDef  hadc1;
TIM_HandleTypeDef  htim2;
I2C_HandleTypeDef  hi2c1;
UART_HandleTypeDef huart1;

/* ---- Application config ---- */
#define RESET_BTN_PORT   GPIOB
#define RESET_BTN_PIN    GPIO_PIN_0

#define TILT_SENSOR_PORT GPIOB
#define TILT_SENSOR_PIN  GPIO_PIN_3

#define SAMPLE_INTERVAL_MS  500U
#define SMS_COOLDOWN_MS     60000U
#define REGISTERED_NUMBER   "+91XXXXXXXXXX"

static EngineLock_HandleTypeDef hEngine;
static AlertIO_HandleTypeDef    hAlert;
static TiltSensor_HandleTypeDef hTilt;

static uint32_t lastSampleTick = 0;
static uint32_t lastSmsTick    = 0;

/* ---- Forward declarations for HAL init stubs (provided by CubeMX
 *      normally; declared here so this file compiles standalone) ---- */
void SystemClock_Config(void);
static void MX_GPIO_Init(void);
static void MX_ADC1_Init(void);
static void MX_TIM2_Init(void);
static void MX_I2C1_Init(void);
static void MX_USART1_UART_Init(void);

static void HandleAlcoholDetected(uint16_t level);
static void HandleTiltDetected(void);
static void ResetSystem(void);

int main(void)
{
    HAL_Init();
    SystemClock_Config();

    MX_GPIO_Init();
    MX_ADC1_Init();
    MX_TIM2_Init();
    MX_I2C1_Init();
    MX_USART1_UART_Init();

    /* ---- Module init ---- */
    AlcoholSensor_Init(&hadc1);

    hEngine.in1_port   = GPIOA;
    hEngine.in1_pin    = GPIO_PIN_1;
    hEngine.in2_port   = GPIOA;
    hEngine.in2_pin    = GPIO_PIN_2;
    hEngine.pwm_timer  = &htim2;
    hEngine.pwm_channel = TIM_CHANNEL_1;
    EngineLock_Init(&hEngine);

    hAlert.buzzer_port = GPIOB;
    hAlert.buzzer_pin  = GPIO_PIN_1;
    hAlert.led_port    = GPIOB;
    hAlert.led_pin     = GPIO_PIN_2;
    AlertIO_Init(&hAlert);

    hTilt.port        = TILT_SENSOR_PORT;
    hTilt.pin         = TILT_SENSOR_PIN;
    hTilt.active_low  = 1U;   /* set to 0 if your module is active-high */
    TiltSensor_Init(&hTilt);

    LCD_Init(&hi2c1);
    LCD_Clear();
    LCD_SetCursor(0, 0);
    LCD_Print("Engine Locking");
    LCD_SetCursor(0, 1);
    LCD_Print("System");
    HAL_Delay(2000);

    GSM_Init(&huart1);

    LCD_Clear();
    LCD_SetCursor(0, 0);
    LCD_Print("System Ready");
    HAL_Delay(1000);
    LCD_Clear();

    while (1)
    {
        uint32_t now = HAL_GetTick();

        /* Manual reset / override button */
        if (HAL_GPIO_ReadPin(RESET_BTN_PORT, RESET_BTN_PIN) == GPIO_PIN_RESET)
        {
            ResetSystem();
            HAL_Delay(300); /* crude debounce */
        }

        if ((now - lastSampleTick) >= SAMPLE_INTERVAL_MS)
        {
            lastSampleTick = now;

            uint16_t level = AlcoholSensor_Read();
            uint8_t  tilted = TiltSensor_Poll(&hTilt);
            char line[17];

            snprintf(line, sizeof(line), "Alcohol:%5u", level);
            LCD_SetCursor(0, 0);
            LCD_Print(line);

            if (tilted)
            {
                HandleTiltDetected();
            }
            else if (AlcoholSensor_IsDetected(level))
            {
                HandleAlcoholDetected(level);
            }
            else if (!EngineLock_IsLocked(&hEngine))
            {
                LCD_SetCursor(0, 1);
                LCD_Print("Status: Normal  ");
                AlertIO_Off(&hAlert);
            }
        }
    }
}

static void HandleAlcoholDetected(uint16_t level)
{
    LCD_SetCursor(0, 1);
    LCD_Print("Alcohol Detected");

    AlertIO_On(&hAlert);
    AlertIO_Beep(&hAlert, 150, 150);

    if (!EngineLock_IsLocked(&hEngine))
    {
        EngineLock_Stop(&hEngine);
    }

    uint32_t now = HAL_GetTick();
    if ((now - lastSmsTick) >= SMS_COOLDOWN_MS)
    {
        lastSmsTick = now;

        char location[64];
        char message[128];

        GSM_GetLocation(location, sizeof(location));
        snprintf(message, sizeof(message),
                 "Alcohol_Detected! Level=%u Location: %s",
                 level, location);

        LCD_Clear();
        LCD_Print("Sending Alert...");
        GSM_SendSMS(REGISTERED_NUMBER, message);
        LCD_Clear();
        LCD_Print("Alert Sent");
        HAL_Delay(1000);
        LCD_Clear();
    }
}

/**
 * @brief Vehicle tilt/rollover detected: lock the engine immediately
 *        (independent of alcohol level) and send a location alert,
 *        since a sharp tilt typically indicates a crash or rollover.
 */
static void HandleTiltDetected(void)
{
    LCD_SetCursor(0, 1);
    LCD_Print("TILT DETECTED!  ");

    AlertIO_On(&hAlert);
    AlertIO_Beep(&hAlert, 100, 100);
    AlertIO_Beep(&hAlert, 100, 100);

    if (!EngineLock_IsLocked(&hEngine))
    {
        EngineLock_Stop(&hEngine);
    }

    uint32_t now = HAL_GetTick();
    if ((now - lastSmsTick) >= SMS_COOLDOWN_MS)
    {
        lastSmsTick = now;

        char location[64];
        char message[128];

        GSM_GetLocation(location, sizeof(location));
        snprintf(message, sizeof(message),
                 "Tilt_Detected! Possible rollover. Location: %s",
                 location);

        LCD_Clear();
        LCD_Print("Sending Alert...");
        GSM_SendSMS(REGISTERED_NUMBER, message);
        LCD_Clear();
        LCD_Print("Alert Sent");
        HAL_Delay(1000);
        LCD_Clear();
    }
}

static void ResetSystem(void)
{
    LCD_Clear();
    LCD_Print("Resetting...");
    EngineLock_Start(&hEngine);
    AlertIO_Off(&hAlert);
    TiltSensor_Reset();
    HAL_Delay(800);
    LCD_Clear();
}

/* -------------------------------------------------------------------
 * UART RX-complete callback: forwards to the GSM module's own handler.
 * ------------------------------------------------------------------- */
void HAL_UART_RxCpltCallback(UART_HandleTypeDef *huart)
{
    if (huart->Instance == USART1)
    {
        extern void GSM_UART_RxCallback(void);
        GSM_UART_RxCallback();
    }
}

/* -------------------------------------------------------------------
 * The following MX_*_Init()/SystemClock_Config() stubs are normally
 * generated in full by STM32CubeMX based on your exact pin assignment
 * and clock tree. Fill these in from your own .ioc project, or paste
 * the generated versions here -- they are intentionally left as
 * lightweight placeholders since their exact contents depend on your
 * chosen STM32 part and pinout.
 * ------------------------------------------------------------------- */

void SystemClock_Config(void)
{
    /* Generated by CubeMX for your specific board/crystal. */
}

static void MX_GPIO_Init(void)
{
    GPIO_InitTypeDef GPIO_InitStruct = {0};

    __HAL_RCC_GPIOA_CLK_ENABLE();
    __HAL_RCC_GPIOB_CLK_ENABLE();

    /* Motor driver direction pins */
    GPIO_InitStruct.Pin   = GPIO_PIN_1 | GPIO_PIN_2;
    GPIO_InitStruct.Mode  = GPIO_MODE_OUTPUT_PP;
    GPIO_InitStruct.Pull  = GPIO_NOPULL;
    GPIO_InitStruct.Speed = GPIO_SPEED_FREQ_LOW;
    HAL_GPIO_Init(GPIOA, &GPIO_InitStruct);

    /* Buzzer + status LED */
    GPIO_InitStruct.Pin   = GPIO_PIN_1 | GPIO_PIN_2;
    HAL_GPIO_Init(GPIOB, &GPIO_InitStruct);

    /* Reset button, active low */
    GPIO_InitStruct.Pin  = RESET_BTN_PIN;
    GPIO_InitStruct.Mode = GPIO_MODE_INPUT;
    GPIO_InitStruct.Pull = GPIO_PULLUP;
    HAL_GPIO_Init(RESET_BTN_PORT, &GPIO_InitStruct);

    /* Tilt sensor pin itself is configured inside TiltSensor_Init(),
     * called from main() after this function returns. */
}

static void MX_ADC1_Init(void)
{
    /* Generated by CubeMX: configures hadc1 for single-channel,
     * software-triggered conversion on the MQ-3 analog pin. */
}

static void MX_TIM2_Init(void)
{
    /* Generated by CubeMX: configures htim2 Channel 1 as PWM output
     * driving the motor driver's ENABLE pin. */
}

static void MX_I2C1_Init(void)
{
    /* Generated by CubeMX: configures hi2c1 (100kHz/400kHz) for the
     * LCD1602 I2C backpack. */
}

static void MX_USART1_UART_Init(void)
{
    /* Generated by CubeMX: configures huart1 at 9600 baud, 8N1,
     * matching the SIM800C's default UART settings. */
}
